#cloud-config
hostname: coreos-seed-01
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDu0CTAN750SR4y8Rr/2Rx3DIq8qwhl3E/0XtiEDK45eYXeGlVc58YHg1GLXyQPByiqsc2JcQfLMp/fCWdJYkWsExus91M99c1UwCMUOwpfDW0h8Hvv61/7mSU6NmO8RjN6fhyo3pLWE34tYY1Nt8mxB/T7zfSTlXZ28UuQAv4i+Lk8bW46Npk1byVLbx28LDtUy7vp2wfCKqZvOuT3KMxafBkR7geWSHHpW1ifNi6diZOpEXZFJ9dwfKUv3LsrogloA3YHNIRVydqDyFG6vRYI9Wp7nHFYv91HKPGevEnhka0sql2J4w/TegDIUJC0/pid8hbPfZgG1ekFWh851l9t

coreos:

  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start

  write_files:
    -   content: |
          [Match]
          Name=enp0s3

          [Network]
          Gateway=10.0.0.254
          Address=10.0.0.1/24
          DNS=8.8.8.8

        path: /etc/systemd/network/00-static.network

  units:
    - name: systemd-networkd
      command: restart



  etcd2:
    name: coreos-seed-01
    initial-cluster-state: new
    initial-cluster-token: etcd-initial-cluster
    initial-cluster: "coreos-seed-01=http://10.0.0.1:2380,coreos-seed-02=http://10.0.0.2:2380,coreos-seed-03=http://10.0.0.3:2380,coreos-seed-04=http://10.0.0.4:2380,coreos-seed-05=http://10.0.0.5:2380"
    initial-advertise-peer-urls: "http://10.0.0.1:2380"
    listen-peer-urls: "http://10.0.0.1:2380"
    listen-client-urls: "http://10.0.0.1:2379,http://localhost:2379"

  update:
    reboot-strategy: etcd-lock
    group: stable
    server: "http://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso"

  fleet:
    metadata: "region=localhost,provider=virtualbox,environment=demo,role=seed"