#cloud-config
ssh_authorized_keys:
	- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDu0CTAN750SR4y8Rr/2Rx3DIq8qwhl3E/0XtiEDK45eYXeGlVc58YHg1GLXyQPByiqsc2JcQfLMp/fCWdJYkWsExus91M99c1UwCMUOwpfDW0h8Hvv61/7mSU6NmO8RjN6fhyo3pLWE34tYY1Nt8mxB/T7zfSTlXZ28UuQAv4i+Lk8bW46Npk1byVLbx28LDtUy7vp2wfCKqZvOuT3KMxafBkR7geWSHHpW1ifNi6diZOpEXZFJ9dwfKUv3LsrogloA3YHNIRVydqDyFG6vRYI9Wp7nHFYv91HKPGevEnhka0sql2J4w/TegDIUJC0/pid8hbPfZgG1ekFWh851l9t

rancher:
  network:
    interfaces:
      eth0:
        dhcp: true

    dns:
      nameservers:
    	- 8.8.8.8

    hostname: rancher-master